<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pendaftar_model extends CI_Model
{

    public $table = 'pendaftar';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('asal_sekolah', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('nilai_ujian', $q);
	$this->db->or_like('hubungan_wali', $q);
	$this->db->or_like('nama_ortu', $q);
	$this->db->or_like('pekerjaan_ortu', $q);
	$this->db->or_like('alamat_ortu', $q);
	$this->db->or_like('email_ortu', $q);
	$this->db->or_like('hp_ortu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('asal_sekolah', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal_lahir', $q);
	$this->db->or_like('nilai_ujian', $q);
	$this->db->or_like('hubungan_wali', $q);
	$this->db->or_like('nama_ortu', $q);
	$this->db->or_like('pekerjaan_ortu', $q);
	$this->db->or_like('alamat_ortu', $q);
	$this->db->or_like('email_ortu', $q);
	$this->db->or_like('hp_ortu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pendaftar_model.php */
/* Location: ./application/models/Pendaftar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-18 19:07:05 */
/* http://harviacode.com */