<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengunjung extends CI_Controller
{
    private $container = "admin/container";
    private $defaultPageAttribute = array(
                        'title' => "Dashboard",
                        'subtitle' => array("Pengunjung"),
                        'bootstraps' => array(),
                        'scripts' => array(),
                        'content' => "admin/",
                        );

    function __construct()
    {
        parent::__construct();
        $this->load->model('Pengunjung_model');
        if ($this->session->userdata("level")!="admin") {
            redirect("Home");
        }
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        $sorting = $this->input->post('sorting', TRUE);
        $sortingorder = $this->input->post('sortingorder', TRUE);
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'admin/Pengunjung/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'admin/Pengunjung/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'admin/Pengunjung/index';
            $config['first_url'] = base_url() . 'admin/Pengunjung/index';
        }

        if ($sorting != NULL) {
            $this->Pengunjung_model->orderColumn = $sorting;
        }
        if ($sortingorder != NULL) {
            $this->Pengunjung_model->defaultorder = ($sortingorder=="ASC"?"DESC":"ASC");
        };

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Pengunjung_model->total_rows($q);
        $pengunjung = $this->Pengunjung_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $this->defaultPageAttribute['content'] = "admin/pengunjung/pengunjung_list";
        $this->defaultPageAttribute['title'] = "Data Pengunjung";
        $this->defaultPageAttribute['scripts'] = array(
            'assets/aceadmin/js/admin-pengunjung.js'
        );
        $data = array(
            'pengunjung_data' => $pengunjung,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'sorting' => $sorting,
            'sortingorder' => $sortingorder,
            'action' => $config['base_url'],
            'PageAttribute' => $this->defaultPageAttribute
        );
        $this->load->view($this->container, $data);
    }
    
    public function delete($id) 
    {
        $row = $this->Pengunjung_model->get_by_id($id);

        if ($row) {
            $this->Pengunjung_model->delete($id);
            $this->session->set_flashdata('ci_flash_message', 'Data berhasil dihapus');
            redirect(site_url('admin/Pengunjung'));
        } else {
            $this->session->set_flashdata('ci_flash_message', 'Upsss, data yang anda cari tidak ditemukan...');
            redirect(site_url('admin/Pengunjung'));
        }
    }
    
    public function ajaxRequest_delete() 
    {
        $d = $this->input->post('data', TRUE);
        foreach ($d as $key => $value) {
            $this->Pengunjung_model->delete($value["id"]);
        };

        echo "success";
    }

}

/* End of file Pengunjung.php */
/* Location: ./application/controllers/Pengunjung.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-26 08:45:13 */
/* http://harviacode.com */